### ISSUE TITLE
Add a way to add regexp to filter composable that are known to be unstable.

### ISSUE THREAD

**Issue by Tolriq** [jayasuryat/mendable#33]
**Is your feature request related to a problem? Please describe.**
Currently we can't filter and the report will contains all the composables that are not stable.

My app is highly modularized with lots of "screens" and all screen root composable always follows the same naming with a passed viewmodel that is know to be not stable.

![image](https://github.com/jayasuryat/mendable/assets/932609/e53ef0b4-c9d1-4753-b241-cb0a9d1691af)

**Describe the solution you'd like**
I'd like to be able to exclude all composable with a regex like `.*ScreenContent$` to reduce a lot the noise of the output.

**Describe alternatives you've considered**
No idea

**Comment by jayasuryat** [comment]
Hi @Tolriq,

Yes, I've faced the same issue. And it does contribute to some noise. 

Adding a search field at the top of the generated report (with support for regex) sounds like _a generally nice to have_ feature. Do you think this will suffice your usecase? Or do have something else in your mind?

---

###### On a side note:
######  Applying a regex filter will only work in cases like yours, who have have a particular naming scheme for their root composables. It will not work for the vast majority of others who might not follow such a naming scheme. I wonder what could be done to address all of these.

**Comment by Tolriq** [comment]
Since you only work with the compose metrics you don't have access to annotations or anything else in the code.

I don't really see another solution than providing a list of regex / names to be ignored.

My goal is to remove all the noise to quickly find regressions or mistakes without having to deal manually with all the individual files, so not sure a search field would help for that matter I really need an exclude.
100 modules and about 160 "screens" makes really too much noise to be easily used.

**Comment by jayasuryat** [comment]
Yes, I understood you intention.

I forgot to add this bit of detail in the last comment, along with with the regex search (or filter, if you will) there can be `inverse-filter` or `filter-not` checkbox (open for better name suggestions). The implication here is "Filter **out** the items which match the regex" or in other words "Only show items which **do not** match the regex", and this can be toggled on or off.

Again, this how my brain approached this problem.  If you think there is a better way of approaching this problem or any different solution for that matter, I'm open for ideas.

**Comment by Tolriq** [comment]
Well this would still not work for people who can't use a regexp but would need to put a list of things each and every time.

And the stats would be wrong too. (But that depends how you handle them).

Anyway just the filter would already be a nice addition, but a filter at generation allows more flexibility and consistency and proper stats.

**Comment by jayasuryat** [comment]
> Well this would still not work for people who can't use a regexp but would need to put a list of things each and every time.

True, that is what I was addressing in the [first comment](https://github.com/jayasuryat/mendable/issues/33#issuecomment-1727963058)

> ###### On a side note:
> ###### Applying a regex filter will only work in cases like yours, who have have a particular naming scheme for their root composables. It will not work for the vast majority of others who might not follow such a naming scheme. I wonder what could be done to address all of these.

---

> And the stats would be wrong too. (But that depends how you handle them).

Yes, they could be _considered_ wrong (technically it would not be wrong as the overview sections represent the entirety of the data, and not a filtered subset, but I get your point). Stats will not change based on a dynamic filter. 

---

> filter at generation

### Bingo! that is the actual requirement.

So you are suggesting passing a regex as a CLI argument to the jar?

**Comment by Tolriq** [comment]
Well yes I'm sorry if I was not clear from the start, not enough sleep those days.

Would probably need to allow multiple regexp to support more use cases.

**Comment by jayasuryat** [comment]
No worries, @Tolriq.

---

Using regex as a CLI argument could certainly solve your specific use case.

However, I'm not so sure how I feel about this approach. It might not be user-friendly for the majority of cases where projects lack specific naming schemes for composables. In such scenarios, the suggestion here (I'm assuming) would be to pass a regex for each composable that needs to be skipped, effectively creating a list of regex patterns. This process seems a bit cumbersome, especially considering that these values are entered via the command line. So, this feature might end up only catering to a very niche use case and not being that useful in a general purpose sense.

On the other hand, the `HTML-report-filter` sounds like a general purpose feature, which could filter out compostables as per your need, but it may have other undesirable behaviour for you, like the overview stats being _misrepresented_.

Just thinking out loud.

Let me know how you feel.

**Comment by Tolriq** [comment]
The goal is to run that on CI and display the html in the PR.
So HTML filter is nice for one shot things, but not automation. And in all cases having to enter the filter each time when it could be passed in a script that call this tool is suboptimal.

Ultimately having a compare with a previous version would be too but that's another story.

Anyway no problem if you think this is not a common need. I should probably motivate myself to build something, but was hoping to have found something all done.

**Comment by jayasuryat** [comment]
> The goal is to run that on CI and display the html in the PR.

Oh, that's the actual use-case. Yes, the `HTML-filter` would not be of much use there.

---

Thanks for understanding. And sorry, as of now, I don't think this is much of a common use case to bake this feature into the tool. 

And if I change my mind as I encounter more such use cases, I'll let you know.

---

If you are planning to build something by yourself, this project is also available as [a set of library dependencies](https://jayasuryat.github.io/mendable/howto/Library/). Could give you a significant head-start.

> Ultimately having a compare with a previous version would be too but that's another story.

On another note, I'm not a 100% certain what exactly you meant here. But for comparing stats with a previous version, the `JSON` output of mendable would be more suitable. If it fits your bill. You can export a `JSON` report by passing `-eType json` in the CLI args, you can see full list of supported options [here](https://jayasuryat.github.io/mendable/howto/Cli/#configuration).

**Comment by Tolriq** [comment]
Well this is the end goal, having anything to filter now to gain time on fixing my code is a gain :)

With that said no problem if you don't see the benefit, don't really have time to build something right now, so will keep an eye here if you change your mind.
